name: face_recog
channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - numpy>=1.24
  - pyyaml>=6.0
  - pydantic>=2.0
  - requests>=2.31
  - opencv>=4.8
  - pip:
      - insightface>=0.7
      - onnxruntime-gpu>=1.16
      - python-dotenv>=1.0
      - watchdog>=3.0
      - fastapi>=0.100
      - uvicorn>=0.20
      - jinja2>=3.1
      - python-multipart>=0.0.6
