camera:
  source: webcam # webcam | rtsp
  webcam_index: 0 # 0 | null
  rtsp_url: null # null | rtsp_url
  process_fps: 5
  preview: true # true | false

recognition:
  threshold: 0.30
  min_consecutive_hits: 2

presence:
  grace_seconds: 3 # for testing, default: 20 sec
  absent_seconds: 10 # for testing, default 300 sec (5 menit)

storage:
  data_dir: "./data"
  snapshot_enabled: true
  snapshot_retention_days: 14

target:
  spg_ids: ["001","002","003","004","005","006","007"]
  outlet_id: "OUTLET_DEV"
  camera_id: "CAM01"
